name: Feature Request
description: Suggest a new feature or enhancement for Operative
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below to help us understand your idea.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: "A clear and concise description of what the problem is. Ex. I'm always frustrated when..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.
      placeholder: Other approaches you've thought about...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of Operative does this relate to?
      options:
        - Orchestrator
        - Agent Runner
        - MCP Client/Server
        - Chrome AI Integration
        - UI/Side Panel
        - Knowledge Service
        - Other
    validations:
      required: true

  - type: dropdown
    id: willing-to-contribute
    attributes:
      label: Willing to Contribute
      description: Would you be willing to help implement this feature?
      options:
        - "Yes, I'd like to implement this"
        - "Yes, I can help with guidance"
        - "No, but I'd like to see it implemented"
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots about the feature request here.
